---
version: '3'

services:

  scala_machine:
    image: 'twa/scala:latest'
    build:
      context: docker/
    hostname: scala_machine
    environment:
      TZ: ${TZ_SET}      
    volumes:
      - ./scripts:/scripts
    extra_hosts:
      - "moby:127.0.0.1"      

 